[tool.mypy]
python_version = "3.11"
strict = true
packages = ["nighio", "tests"]
exclude = ["bench.py"]

[tool.coverage.run]
source = ["nighio"]

[tool.black]
line-length = 100
target-version = ["py36"]
skip-string-normalization = true

[tool.isort]
py_version=36
line_length = 100

[tool.flake8]
max-line-length = 100
ignore = ["E402", "E704", "E203"]
exclude = ["tests/bench.py"]
